import { useState } from "react";
import axios from "axios";

const API = "http://localhost:8000";

const REPORT_TYPES = [
  { label: "PERSON INTELLIGENCE", value: "person", placeholder: "Enter person name..." },
  { label: "CYBER THREAT", value: "threat", placeholder: "Enter IP or domain..." },
  { label: "GEO INTELLIGENCE", value: "geo", placeholder: "Enter location..." },
  { label: "NEWS ANALYSIS", value: "news", placeholder: "Enter topic..." },
  { label: "GENERAL OSINT", value: "general", placeholder: "Enter any target..." },
];

function exportTxt(r) {
  const content = `GODS EYE INTELLIGENCE REPORT
================================
Type: ${r.type.toUpperCase()}
Target: ${r.target}
Generated: ${r.timestamp}
================================

${r.content}

--- END OF REPORT ---
Generated by God's Eye OMNIVISION Intelligence Platform
For educational and legal use only.`;
  const blob = new Blob([content], { type: "text/plain" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `gods_eye_${r.type}_${r.target.replace(/\s/g, "_")}_${Date.now()}.txt`;
  a.click();
  URL.revokeObjectURL(url);
}

function exportPdf(r) {
  const htmlContent = `<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<title>God's Eye Intelligence Report</title>
<style>
  @import url('https://fonts.googleapis.com/css2?family=Courier+Prime&display=swap');
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Courier Prime', 'Courier New', monospace; background: #fff; color: #1a1a1a; padding: 40px; }
  .header { border-bottom: 3px solid #cc0000; padding-bottom: 20px; margin-bottom: 24px; }
  .logo { font-size: 28px; font-weight: bold; color: #cc0000; letter-spacing: 6px; }
  .subtitle { font-size: 11px; color: #666; letter-spacing: 3px; margin-top: 4px; }
  .meta-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 24px; }
  .meta-box { padding: 10px; border: 1px solid #ddd; border-top: 2px solid #cc0000; }
  .meta-label { font-size: 9px; color: #cc0000; letter-spacing: 2px; margin-bottom: 4px; }
  .meta-value { font-size: 13px; font-weight: bold; color: #1a1a1a; }
  .report-body { line-height: 1.8; font-size: 12px; white-space: pre-wrap; color: #1a1a1a; }
  .section-title { font-size: 14px; font-weight: bold; color: #cc0000; margin: 16px 0 8px; letter-spacing: 2px; }
  .footer { margin-top: 40px; padding-top: 12px; border-top: 1px solid #ddd; font-size: 9px; color: #999; text-align: center; letter-spacing: 1px; }
  .watermark { color: #cc000022; font-size: 60px; position: fixed; top: 40%; left: 50%; transform: translate(-50%, -50%) rotate(-30deg); pointer-events: none; font-weight: bold; letter-spacing: 8px; }
  @media print { body { padding: 20px; } .watermark { display: block; } }
</style>
</head>
<body>
<div class="watermark">EDUCATIONAL USE ONLY</div>

<div class="header">
  <div class="logo">👁 GOD'S EYE</div>
  <div class="subtitle">OMNIVISION INTELLIGENCE PLATFORM — OFFICIAL REPORT</div>
</div>

<div class="meta-grid">
  <div class="meta-box">
    <div class="meta-label">REPORT TYPE</div>
    <div class="meta-value">${r.type.toUpperCase()}</div>
  </div>
  <div class="meta-box">
    <div class="meta-label">TARGET</div>
    <div class="meta-value">${r.target}</div>
  </div>
  <div class="meta-box">
    <div class="meta-label">GENERATED</div>
    <div class="meta-value">${r.timestamp}</div>
  </div>
</div>

<div class="report-body">${r.content.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</div>

<div class="footer">
  <div>GOD'S EYE OMNIVISION INTELLIGENCE PLATFORM v1.0</div>
  <div style="margin-top:4px">DEVELOPED BY ABHYAS KATHURIA — PRESIDENCY UNIVERSITY, BANGALORE</div>
  <div style="margin-top:4px">FOR EDUCATIONAL AND LEGAL USE ONLY — ALL DATA FROM PUBLIC SOURCES</div>
</div>
</body>
</html>`;

  const blob = new Blob([htmlContent], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  const win = window.open(url, "_blank");
  if (win) {
    win.onload = () => {
      setTimeout(() => {
        win.print();
        URL.revokeObjectURL(url);
      }, 500);
    };
  }
}

function exportJson(r) {
  const data = {
    platform: "God's Eye OMNIVISION",
    version: "1.0",
    report_type: r.type,
    target: r.target,
    generated: r.timestamp,
    content: r.content,
    disclaimer: "Educational and legal use only. All data from public sources."
  };
  const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = `gods_eye_${r.type}_${r.target.replace(/\s/g, "_")}_${Date.now()}.json`;
  a.click();
  URL.revokeObjectURL(url);
}

export default function Reports() {
  const [reportType, setReportType] = useState("general");
  const [target, setTarget] = useState("");
  const [report, setReport] = useState(null);
  const [loading, setLoading] = useState(false);
  const [savedReports, setSavedReports] = useState([]);

  const generateReport = async (overrideTarget = null, overrideType = null) => {
    const targetVal = (typeof overrideTarget === "string") ? overrideTarget : target;
    const typeVal = (typeof overrideType === "string") ? overrideType : reportType;

    if (!targetVal.trim()) return;
    setLoading(true);
    setReport(null);
    try {
      const res = await axios.post(`${API}/ai/report`, {
        type: typeVal,
        data: { target: targetVal, type: typeVal }
      });
      const newReport = {
        id: Date.now(),
        type: typeVal,
        target: targetVal,
        content: res.data.report,
        timestamp: new Date().toLocaleString("en-IN", { timeZone: "Asia/Kolkata" })
      };
      setReport(newReport);
      setSavedReports(prev => [newReport, ...prev.slice(0, 9)]);
    } catch (e) {
      console.error(e);
    }
    setLoading(false);
  };

  const s = {
    section: { marginBottom: "16px", padding: "12px", border: "1px solid #440000", background: "#060000" },
    title: { color: "#ff0000", fontSize: "11px", letterSpacing: "3px", marginBottom: "8px" },
  };

  return (
    <div style={{ display: "flex", height: "100%", overflow: "hidden", background: "#000000" }}>

      {/* Left Panel */}
      <div style={{ width: "280px", display: "flex", flexDirection: "column",
        gap: "12px", padding: "12px", borderRight: "1px solid #440000",
        background: "#030000", overflowY: "auto" }}>

        <div style={{ color: "#ff0000", fontSize: "11px", letterSpacing: "3px",
          paddingBottom: "8px", borderBottom: "1px solid #440000" }}>
          REPORT GENERATOR
        </div>

        <div>
          <div style={{ color: "#882222", fontSize: "11px", marginBottom: "6px", letterSpacing: "1px" }}>
            REPORT TYPE
          </div>
          {REPORT_TYPES.map(t => (
            <button key={t.value} onClick={() => setReportType(t.value)}
              style={{ width: "100%", padding: "8px", marginBottom: "4px",
                fontSize: "11px", letterSpacing: "1px", cursor: "pointer",
                fontFamily: "Courier New", textAlign: "left",
                background: reportType === t.value ? "#1a0000" : "#060000",
                border: `1px solid ${reportType === t.value ? "#ff0000" : "#330000"}`,
                color: reportType === t.value ? "#ff0000" : "#552222" }}>
              {t.label}
            </button>
          ))}
        </div>

        <div style={{ borderTop: "1px solid #220000" }} />

        <div>
          <div style={{ color: "#882222", fontSize: "11px", marginBottom: "6px", letterSpacing: "1px" }}>
            TARGET
          </div>
          <input type="text"
            placeholder={REPORT_TYPES.find(t => t.value === reportType)?.placeholder}
            value={target} onChange={e => setTarget(e.target.value)}
            onKeyDown={e => e.key === "Enter" && generateReport()}
            style={{ width: "100%", background: "#060000", border: "1px solid #440000",
              borderLeft: "3px solid #ff0000", color: "#ff2222", fontFamily: "Courier New",
              fontSize: "11px", padding: "8px 12px" }} />

          <button onClick={generateReport} disabled={loading || !target.trim()}
            style={{ width: "100%", padding: "8px", marginTop: "6px", fontSize: "11px",
              letterSpacing: "1px", cursor: "pointer", fontFamily: "Courier New",
              background: target ? "#1a0000" : "#060000",
              border: `1px solid ${target ? "#ff0000" : "#440000"}`,
              color: target ? "#ff0000" : "#662222" }}>
            {loading ? "GENERATING..." : "GENERATE REPORT"}
          </button>
        </div>

        <div style={{ borderTop: "1px solid #220000" }} />
        <div style={{ color: "#882222", fontSize: "11px", letterSpacing: "1px" }}>
          QUICK SAMPLES
        </div>
        {[
          { label: "[PERSON] Abhyas Kathuria", type: "person", target: "Abhyas Kathuria" },
          { label: "[CYBER] Malware IP 8.8.8.8", type: "threat", target: "8.8.8.8" },
          { label: "[GEO] Mumbai, India", type: "geo", target: "Mumbai, India" },
          { label: "[NEWS] Quantum Computing", type: "news", target: "Quantum Computing" },
          { label: "[GENERAL] Presidency Univ", type: "general", target: "Presidency University" },
        ].map((smp, i) => (
          <button key={i} onClick={() => {
            setReportType(smp.type);
            setTarget(smp.target);
            generateReport(smp.target, smp.type);
          }}
            style={{
              width: "100%", padding: "6px 8px", marginBottom: "4px",
              fontSize: "11px", cursor: "pointer", fontFamily: "Courier New",
              textAlign: "left", background: "#060000",
              border: "1px solid #330000", color: "#552222",
            }}>
            {smp.label}
          </button>
        ))}

        {/* Saved Reports */}
        {savedReports.length > 0 && (
          <>
            <div style={{ borderTop: "1px solid #220000" }} />
            <div style={{ color: "#882222", fontSize: "11px", letterSpacing: "1px" }}>
              SAVED ({savedReports.length})
            </div>
            {savedReports.map((r) => (
              <div key={r.id} onClick={() => setReport(r)}
                style={{ padding: "6px 8px", marginBottom: "4px", cursor: "pointer",
                  background: report?.id === r.id ? "#1a0000" : "#060000",
                  border: `1px solid ${report?.id === r.id ? "#ff0000" : "#330000"}` }}>
                <div style={{ fontSize: "10px", color: "#ff4400" }}>{r.type.toUpperCase()}</div>
                <div style={{ fontSize: "11px", color: "#882222" }}>{r.target}</div>
                <div style={{ fontSize: "9px", color: "#330000" }}>{r.timestamp}</div>
              </div>
            ))}
          </>
        )}
      </div>

      {/* Right Panel */}
      <div style={{ flex: 1, overflow: "hidden", display: "flex", flexDirection: "column" }}>

        <div style={{ padding: "12px 16px", borderBottom: "1px solid #330000",
          background: "#060000", display: "flex", alignItems: "center", gap: "12px" }}>
          <div style={{ color: "#ff0000", fontSize: "11px", letterSpacing: "3px" }}>
            INTELLIGENCE REPORTS
          </div>

          {/* Export buttons */}
          {report && (
            <div style={{ marginLeft: "auto", display: "flex", gap: "6px" }}>
              {[
                { label: "PDF", action: () => exportPdf(report) },
                { label: "TXT", action: () => exportTxt(report) },
                { label: "JSON", action: () => exportJson(report) },
              ].map((btn, i) => (
                <button key={i} onClick={btn.action}
                  style={{ padding: "5px 12px", fontSize: "10px", letterSpacing: "1px",
                    cursor: "pointer", fontFamily: "Courier New",
                    background: btn.label === "PDF" ? "#1a0000" : "#060000",
                    border: `1px solid ${btn.label === "PDF" ? "#ff0000" : "#440000"}`,
                    color: btn.label === "PDF" ? "#ff0000" : "#882222" }}>
                  EXPORT {btn.label}
                </button>
              ))}
            </div>
          )}
        </div>

        <div style={{ flex: 1, overflowY: "auto", padding: "16px" }}>

          {!report && !loading && (
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center",
              justifyContent: "center", height: "100%", color: "#220000" }}>
              <div style={{ fontSize: "48px", marginBottom: "16px" }}>[ R ]</div>
              <div style={{ fontSize: "13px", letterSpacing: "3px" }}>SELECT TYPE AND ENTER TARGET</div>
              <div style={{ fontSize: "11px", marginTop: "8px", color: "#150000" }}>
                Export as PDF, TXT, or JSON
              </div>
            </div>
          )}

          {loading && (
            <div style={{ display: "flex", flexDirection: "column", alignItems: "center",
              justifyContent: "center", height: "100%", gap: "12px" }}>
              <div style={{ color: "#ff0000", fontSize: "11px", letterSpacing: "3px" }}
                className="animate-pulse">
                GENERATING INTELLIGENCE REPORT...
              </div>
            </div>
          )}

          {report && !loading && (
            <div>
              <div style={s.section}>
                <div style={s.title}>REPORT DETAILS</div>
                <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: "8px" }}>
                  {[
                    ["TYPE", report.type.toUpperCase()],
                    ["TARGET", report.target],
                    ["GENERATED", report.timestamp],
                  ].map(([k, v]) => (
                    <div key={k} style={{ padding: "8px", border: "1px solid #330000", background: "#0d0000" }}>
                      <div style={{ fontSize: "10px", color: "#ff4400", marginBottom: "4px" }}>{k}</div>
                      <div style={{ fontSize: "11px", color: "#882222" }}>{v}</div>
                    </div>
                  ))}
                </div>
              </div>

              <div style={{ ...s.section, borderColor: "#ff0000" }}>
                <div style={s.title}>INTELLIGENCE REPORT</div>
                <pre style={{ color: "#882222", fontSize: "11px",
                  whiteSpace: "pre-wrap", fontFamily: "Courier New", lineHeight: "1.8" }}>
                  {report.content}
                </pre>
              </div>

              {/* Deepfake warning */}
              <div style={{ padding: "10px 14px", background: "#0a0a00",
                border: "1px solid #444400", borderLeft: "3px solid #888800" }}>
                <div style={{ fontSize: "10px", color: "#888800", letterSpacing: "1px" }}>
                  ⚠ INTEGRITY NOTICE: In 2026, AI-generated synthetic media is common.
                  Always cross-verify faces, quotes, and claims from multiple independent sources.
                  God's Eye analyzes public data only — results may include AI-generated content.
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
